from fastapi import APIRouter, BackgroundTasks
from ..models import AnalysisResult, ArchitectureGraph
import asyncio
import json

router = APIRouter()

target_code_template = """package com.example.shop.controllers;

import com.example.shop.services.OrderService;
import com.example.shop.models.Order;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/orders")
public class OrderController {
    
    @Autowired
    private OrderService orderService;

    @PostMapping
    public ResponseEntity<Order> createOrder(@RequestBody Order orderData) {
        // Implementation generated by ReForge
        return ResponseEntity.ok(orderService.createOrder(orderData));
    }
}"""

async def run_simulated_migration(project_id: str):
    # Import active_connections here to avoid circular import if not careful, or just import it
    from ..main import active_connections
    ws = active_connections.get(project_id)
    if not ws:
        return
        
    async def send_ws(msg_type, msg):
        try:
            await ws.send_text(json.dumps({"type": msg_type, "message": msg}))
        except:
            pass

    await send_ws("status", "RUNNING")
    await send_ws("log", "[Planner] Mapping Express routes to Spring controllers...")
    await asyncio.sleep(1.5)
    
    await send_ws("code", target_code_template)
    await send_ws("log", "[Migration] Generating OrderController.java...")
    await asyncio.sleep(1.5)
    
    await send_ws("log", "[Build] Compiling target project (Maven)...")
    await asyncio.sleep(1.5)
    
    await send_ws("log", "[Build] \x1b[31mCompilation failed: Cannot resolve method createOrder in OrderService\x1b[0m")
    await send_ws("status", "REPAIRING")
    await asyncio.sleep(1.5)
    
    await send_ws("log", "[Repair] Diagnosing missing method implementation...")
    await send_ws("log", "[Repair] Applying patch to OrderService.java...")
    await asyncio.sleep(2.0)
    
    await send_ws("log", "[Build] Recompiling project...")
    await asyncio.sleep(1.5)
    
    await send_ws("log", "[Build] \x1b[32mCompilation successful.\x1b[0m")
    await send_ws("log", "[Test] Running behavioral verification scenarios...")
    await asyncio.sleep(2.0)
    
    await send_ws("log", "[Verification] 18/18 scenarios matched original behavior.")
    await send_ws("status", "COMPLETE")

@router.post("/{project_id}/analyze", response_model=AnalysisResult)
async def analyze_project(project_id: str):
    await asyncio.sleep(1) # simulate work
    return AnalysisResult(
        languages={"JavaScript": "85%", "JSON": "15%"},
        frameworks=["Express"],
        dependencies=["express", "mongoose", "jest"],
        routes=2,
        services=2,
        models=1
    )

@router.get("/{project_id}/architecture", response_model=ArchitectureGraph)
async def get_architecture(project_id: str):
    nodes = [
        {"id": "route1", "type": "default", "data": {"label": "POST /api/orders"}, "position": {"x": 100, "y": 50}},
        {"id": "ctrl1", "type": "default", "data": {"label": "OrderController"}, "position": {"x": 100, "y": 150}},
        {"id": "svc1", "type": "default", "data": {"label": "OrderService"}, "position": {"x": 100, "y": 250}},
        {"id": "svc2", "type": "default", "data": {"label": "PaymentService"}, "position": {"x": 300, "y": 250}},
        {"id": "model1", "type": "default", "data": {"label": "OrderModel"}, "position": {"x": 100, "y": 350}},
        {"id": "db", "type": "default", "data": {"label": "MongoDB"}, "position": {"x": 100, "y": 450}}
    ]
    edges = [
        {"id": "e1", "source": "route1", "target": "ctrl1"},
        {"id": "e2", "source": "ctrl1", "target": "svc1"},
        {"id": "e3", "source": "svc1", "target": "svc2"},
        {"id": "e4", "source": "svc1", "target": "model1"},
        {"id": "e5", "source": "model1", "target": "db"},
    ]
    return ArchitectureGraph(nodes=nodes, edges=edges)

@router.post("/{project_id}/migrate")
async def start_migration(project_id: str, background_tasks: BackgroundTasks):
    background_tasks.add_task(run_simulated_migration, project_id)
    return {"status": "started"}
